baseURL = "http://example.org/"
languageCode = "en-us"
title = "ArmadaNet"
enableGitInfo = true
# disqusShortname = "armadanet"

[params]

  BookMenuBundle = '/menu'
  BookEditPath = 'edit/master/armadanet-website/content'

  # BookComments = true
